server:
    port: 8765

spring:
    application:
        name: nab-api-gateway
    cloud:
        gateway:
            default-filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            discovery:
                locator:
                    enabled: false
                    lower-case-service-id: true
            routes:
                - id: nab-produce-service-id
                  uri: lb://nab-product-service
                  predicates:
                    Path=/product-svc/**
                - id: nab-order-service-id
                  uri: lb://nab-order-service
                  predicates:
                    Path=/order-svc/**
            globalcors:
              corsConfigurations:
                '[/**]':
                  allowedOrigins: "*"
                  allowedMethods: "*"
                  allowedHeaders: "*"
    main:
        web-application-type: reactive
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://admin:admin@localhost:8761/eureka}
    instance:
        preferIpAddress: true

management:
    endpoint.gateway.enabled: true
    endpoints.web.exposure.include: gateway

logging:
    level:
        root: DEBUG
        com: INFO
